### ISSUE TITLE
Question about CI scripts

### ISSUE THREAD

**Issue by Disasm** [rust-embedded/template#3]
I've noticed that CI scripts found in different EWG repos have the following structure:
```bash
set -euxo pipefail

main() {
    # do something...
}

main
```
Is there any reason for such a function-based approach?

As for me, the following code looks much cleaner:
```bash
set -euxo pipefail

# do something...
```

And also in Travis config:
```yml
before_install: set -e

install:
  - bash ci/install.sh
  - export PATH="$PATH:$PWD/gcc/bin:$PWD/qemu"

script:
  - bash ci/script.sh

after_script: set +e
```
Looks like this `before_install: set -e` line is useless as we have `set -euxo pipefail` in scripts. Is there any need for `after_script: set +e` at the end?

cc @rust-embedded/all
